version: "2"
services:
  web:
    container_name: dush-app.apache
    image: gravatalonga/docker-apache2laravel
    ports:
      - "80:80"
    volumes:
      - ./application:/opt/application
    links:
      - php

  php:
    container_name: dush-app.php
    image: gravatalonga/docker-php7.0
    ports:
      - "9001:9001"
      - "22:22"
    volumes:
      - ./application:/opt/application
    links:
      - db
      - redis
      - mailhog

  db:
    container_name: dush-app.maria
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./.database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=control

  redis:
    container_name: dush-app.redis
    image: redis
    ports:
      - "6379:6379"

  mailhog:
    container_name: dush-app.mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"